# This is a basic workflow to help you get started with Actions

name: Hola mundo desde github actions
run-name: Estoy aprendiendo github actions!

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  hola-mundo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v5.0.0

      - name: Dafinir variables
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV

      # Correr el archivo de node o cualquier otro
      - name: Corer script
        run: node index.js

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
