name: Saludo usando variables
run-name: Uso de variables en GitHub Actions
on:
  push:
  workflow_dispatch:
env:
  DIA_DE_SEMANA: Viernes
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola
    steps:
      - name: Saludar
        run: echo "$SALUDO, ${{ vars.NOMBRE }}. Hoy es ${{ env.DIA_DE_SEMANA }}!"
  saludo-secreto:
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola
    steps:
      - name: saludar secretos
        run: echo "$SALUDO, ${{ vars.NOMBRE }}. Tu contrasena es ${{ secrets.CONTRASENA }}!"
