name: Triggers
run-name: ¡Estoy aprendiendo a usar diferentes triggers!
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.js'
  issues:
    types:
      - labeled
  workflow_dispatch:
    inputs:
      lenguaje_favorito:
        description: 'Lenguaje favorito'
        required: true
        type: choice
        options:
        - JavaScript
        - TypeScript
        - Python
      nombre:
        description: 'Tu nombre'
        required: true
        default: Rafa
        type: string
  schedule:
    - cron: '44 13 * * *'
jobs:
  hola-mundo-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Definir nombre
        run: echo "USERNAME=${{ inputs.nombre }}" >> $GITHUB_ENV

      - name: Definir lenguaje
        run: echo "LANGUAGE=${{ inputs.lenguaje_favorito }}" >> $GITHUB_ENV

      - name: Correr script
        run: node index.js

  hola-mundo:
    if: ${{ github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu_latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Definir variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV

      - name: Correr script
        run: node index.js
