name: Saludo usando variables
run-name: Uso de variables en GitHub Actions
on:
  workflow_dispatch
env:
  DIA_DE_SEMANA: Viernes
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola
    steps:
      - name: Saludar
        run: echo "$SALUDO, ${{ vars.NOMBRE }}. Hoy es ${{ env.DIA_DE_SEMANA }}!"